name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: init git submodule model
        run: git submodule init
      - name: update git submodule model
        run: git submodule update
      - name: Build with Gradle
        run: ./gradlew build